## A매출 (2021~2023)

In [ ]:
import pandas as pd

In [ ]:
sales_A = pd.read_excel('A물류센터 매출 2021~2023 배포용.xlsx', sheet_name=None)

print(sales_A.keys())
df1 = sales_A["Result 1"]
df2 = sales_A["Result 2"]

dict_keys(['Result 1', 'Result 2'])

In [ ]:
sales_A = pd.concat([df1, df2], ignore_index=True)

In [ ]:
# 필요 칼럼만 선택
sales_A_cols = ['판매일', '구분', '매출처 우편번호', '판매수량', '중분류', '공급금액', '부가세(과세)']
sales_A = sales_A[sales_A['구분'] == '매출'][sales_A_cols]

sales_A.head()

          판매일  구분  매출처 우편번호  판매수량          중분류   공급금액  부가세(과세)
0  2021-01-04  매출     37806     3  라면,통조림,상온즉석   5400      540
1  2021-01-04  매출     37806     4  라면,통조림,상온즉석  11900     1190
2  2021-01-04  매출     37806     2  라면,통조림,상온즉석   7800      780
3  2021-01-04  매출     37806     3  라면,통조림,상온즉석   5600      560
4  2021-01-04  매출     37806     3  라면,통조림,상온즉석   7100      710

In [ ]:
# 날짜/연도/월/요일 컬럼 생성
sales_A["판매일"] = pd.to_datetime(sales_A['판매일'])
sales_A['연도'] = sales_A['판매일'].dt.year.astype(int)
sales_A['월'] = sales_A['판매일'].dt.month.astype(int)
sales_A['일'] = sales_A['판매일'].dt.day.astype(int)
sales_A['요일'] = sales_A['판매일'].dt.day_name()

In [ ]:
# 계절 컬럼 생성
def get_season(month):
  if month in [12,1,2]:
    return '겨울'
  elif month in [3,4,5]:
    return '봄'
  elif month in [6,7,8]:
    return '여름'
  else:
    return '가을'

sales_A['계절'] = sales_A['월'].apply(get_season)

In [ ]:
sales_A.head()

,판매일,구분,매출처 우편번호,판매수량,중분류,공급금액,부가세(과세),연도,월,일,요일,계절
0,2021-01-04,매출,37806,3,"라면,통조림,상온즉석",5400,540,2021,1,4,Monday,겨울
1,2021-01-04,매출,37806,4,"라면,통조림,상온즉석",11900,1190,2021,1,4,Monday,겨울
2,2021-01-04,매출,37806,2,"라면,통조림,상온즉석",7800,780,2021,1,4,Monday,겨울
3,2021-01-04,매출,37806,3,"라면,통조림,상온즉석",5600,560,2021,1,4,Monday,겨울
4,2021-01-04,매출,37806,3,"라면,통조림,상온즉석",7100,710,2021,1,4,Monday,겨울

### 시도 수동 mapping

In [ ]:
def add_region_codes(df):
    df = df.copy()
    df["매출처_시"] = df["매출처 우편번호"].astype(str).str[:2]
    return df

sales_A = add_region_codes(sales_A)

sales_A.head()

,판매일,구분,매출처 우편번호,판매수량,중분류,공급금액,부가세(과세),연도,월,일,요일,계절,매출처_시
0,2021-01-04,매출,37806,3,"라면,통조림,상온즉석",5400,540,2021,1,4,Monday,겨울,37
1,2021-01-04,매출,37806,4,"라면,통조림,상온즉석",11900,1190,2021,1,4,Monday,겨울,37
2,2021-01-04,매출,37806,2,"라면,통조림,상온즉석",7800,780,2021,1,4,Monday,겨울,37
3,2021-01-04,매출,37806,3,"라면,통조림,상온즉석",5600,560,2021,1,4,Monday,겨울,37
4,2021-01-04,매출,37806,3,"라면,통조림,상온즉석",7100,710,2021,1,4,Monday,겨울,37

In [ ]:
sales_A['매출처_시'].unique()

array(['37', '38', '17', '50', '58', '39', '36', '44', '25', '62', '31',
       '46'], dtype=object)

In [ ]:
# 시도 코드 딕셔너리 생성
si_map = {
    '37' : '경상북도',
    '38' : '경상북도',
    '39' : '경상북도',
    '50' : '경상남도',
    '17' : '경기도',
    '44' : '울산광역시',
    '36' : '경상북도',
    '62' : '광주광역시',
    '31' : '충청남도',
    '46' : '부산광역시',
    '58' : '전라남도',
    '25' : '강원특별자치도'
}

In [ ]:
sales_A["매출처_시"] = sales_A["매출처_시"].map(si_map)
sales_A.head()

,판매일,구분,매출처 우편번호,판매수량,중분류,공급금액,부가세(과세),연도,월,일,요일,계절,매출처_시
0,2021-01-04,매출,37806,3,"라면,통조림,상온즉석",5400,540,2021,1,4,Monday,겨울,경상북도
1,2021-01-04,매출,37806,4,"라면,통조림,상온즉석",11900,1190,2021,1,4,Monday,겨울,경상북도
2,2021-01-04,매출,37806,2,"라면,통조림,상온즉석",7800,780,2021,1,4,Monday,겨울,경상북도
3,2021-01-04,매출,37806,3,"라면,통조림,상온즉석",5600,560,2021,1,4,Monday,겨울,경상북도
4,2021-01-04,매출,37806,3,"라면,통조림,상온즉석",7100,710,2021,1,4,Monday,겨울,경상북도

### 필터링 수행

In [ ]:
# 중분류 신선식품/생수,음료,건강 필터링
A_fresh = sales_A[sales_A['중분류'] == '신선식품'].copy()
A_drinks = sales_A[sales_A['중분류'] == '생수,음료,건강'].copy()

In [ ]:
A_fresh.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26512 entries, 377 to 1461340
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   판매일       26512 non-null  datetime64[ns]
 1   구분        26512 non-null  object
 2   매출처 우편번호  26512 non-null  int64
 3   판매수량      26512 non-null  int64
 4   중분류       26512 non-null  object
 5   공급금액      26512 non-null  int64
 6   부가세(과세)   26512 non-null  int64
 7   연도        26512 non-null  int64
 8   월         26512 non-null  int64
 9   일         26512 non-null  int64
 10  요일        26512 non-null  object
 11  계절        26512 non-null  object
 12  매출처_시     26512 non-null  object
dtypes: datetime64[ns](1), int64(7), object(5)
memory usage: 2.8+ MB

In [ ]:
A_drinks.info()

<class 'pandas.core.frame.DataFrame'>
Index: 194569 entries, 85 to 1461339
Data columns (total 13 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   판매일       194569 non-null  datetime64[ns]
 1   구분        194569 non-null  object
 2   매출처 우편번호  194569 non-null  int64
 3   판매수량      194569 non-null  int64
 4   중분류       194569 non-null  object
 5   공급금액      194569 non-null  int64
 6   부가세(과세)   194569 non-null  int64
 7   연도        194569 non-null  int64
 8   월         194569 non-null  int64
 9   일         194569 non-null  int64
 10  요일        194569 non-null  object
 11  계절        194569 non-null  object
 12  매출처_시     194569 non-null  object
dtypes: datetime64[ns](1), int64(7), object(5)
memory usage: 20.8+ MB

### 데이터셋 추출

In [ ]:
from google.colab import files
A_fresh.to_csv("sales_A_fresh.csv", index=False)
files.download("sales_A_fresh.csv")

A_drinks.to_csv("sales_A_drinks.csv", index=False)
files.download("sales_A_drinks.csv")

In [ ]:
sales_A_fresh = pd.read_csv("sales_A_fresh.csv")
sales_A_fresh.head()

,판매일,구분,매출처 우편번호,판매수량,중분류,공급금액,부가세(과세),연도,월,일,요일,계절,매출처_시
0,2021-01-04,매출,37791,1,신선식품,33000,3300,2021,1,4,Monday,겨울,경상북도
1,2021-01-04,매출,37842,3,신선식품,86900,8690,2021,1,4,Monday,겨울,경상북도
2,2021-01-04,매출,37902,4,신선식품,14500,1450,2021,1,4,Monday,겨울,경상북도
3,2021-01-04,매출,38854,3,신선식품,78400,7840,2021,1,4,Monday,겨울,경상북도
4,2021-01-04,매출,37788,1,신선식품,33000,3300,2021,1,4,Monday,겨울,경상북도

In [ ]:
sales_A_drinks = pd.read_csv("sales_A_drinks.csv")
sales_A_drinks.head()

,판매일,구분,매출처 우편번호,판매수량,중분류,공급금액,부가세(과세),연도,월,일,요일,계절,매출처_시
0,2021-01-04,매출,37581,24,"생수,음료,건강",29500,2950,2021,1,4,Monday,겨울,경상북도
1,2021-01-04,매출,37581,12,"생수,음료,건강",17400,1740,2021,1,4,Monday,겨울,경상북도
2,2021-01-04,매출,37611,1,"생수,음료,건강",20100,2010,2021,1,4,Monday,겨울,경상북도
3,2021-01-04,매출,37611,5,"생수,음료,건강",19600,1960,2021,1,4,Monday,겨울,경상북도
4,2021-01-04,매출,37611,10,"생수,음료,건강",17300,1730,2021,1,4,Monday,겨울,경상북도